language: python
python:
  - "3.6"
  - "3.7"

# enable docker in Travis
services:
  - docker
  
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-\S*)?$/

# command to install dependencies
install:
  - pip install tox-travis

# command to run tests
script:
  - tox
  - docker --version
  - make build
  - docker images
  - docker run `make version` --help

# push images to DockerHub and PyPI on tags
deploy:
  - provider: script
    script: bash docker_deploy.sh
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$DOCKER_PASSWORD"
  - provider: script
    script:  python -m pip install tox && tox -vve pypi_publish
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$TWINE_PASSWORD"
