language: python
python:
  - "2.7"
  - "3.6"
#  - "3.7"

# enable docker in Travis
services:
  - docker

# command to install dependencies
install:
  - pip install tox-travis

# command to run tests
script:
  - tox
  - docker --version
  - make build
  - docker images
  - docker run `make version` --help
