---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealpolicy
  namespace: powerfulseal
data:
  policy.yml: |-
    config:
      runStrategy:
        minSecondsBetweenRuns: 30
        maxSecondsBetweenRuns: 300
    scenarios: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulseal
  namespace: powerfulseal
spec:
  selector:
    matchLabels:
      name: powerfulseal
  replicas: 1
  template:
    metadata:
      labels:
        name: powerfulseal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      serviceAccountName: powerfulseal
      containers:
        - name: powerfulseal
          imagePullPolicy: Always
          image: bloomberg/powerfulseal:3.0.0rc10
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --prometheus-collector
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yml
              subPath: policy.yml
      volumes:
        - name: policyfile
          configMap:
            name: sealpolicy
