---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealpolicy
data:
  policy.yml: |-
    scenarios:
    - name: "delete a random pod in default namespace"
      steps:
      - matches:
        - labels:
            namespace: "default"
            selector: "app=hello"
        filters:
        - randomSample:
            size: 1
        actions:
        - kill:
            probability: 0.77
            force: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulseal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: powerfulseal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      serviceAccountName: powerfulseal
      containers:
        - name: powerfulseal
          image: store/bloomberg/powerfulseal:3.0.0rc0
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --prometheus-collector
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yml
              subPath: policy.yml
      volumes:
        - name: policyfile
          configMap:
            name: sealpolicy
