---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealpolicy
  namespace: powerfulseal
data:
  policy.yml: |-
    config:
      runStrategy:
        minSecondsBetweenRuns: 10
        maxSecondsBetweenRuns: 10
    scenarios:
    - name: "delete a random pod in default namespace"
      steps:
      - podAction:
          matches:
          - labels:
              namespace: "default"
              selector: "app=hello"
          filters:
          - randomSample:
              size: 1
          actions:
          - kill:
              probability: 0.77
              force: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulseal
  namespace: powerfulseal
spec:
  selector:
    matchLabels:
      name: powerfulseal
  replicas: 1
  template:
    metadata:
      labels:
        name: powerfulseal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      serviceAccountName: powerfulseal
      containers:
        - name: powerfulseal
          imagePullPolicy: Always
          image: 445200264539.dkr.ecr.ap-southeast-2.amazonaws.com/pccs/powerfulseal:3.0.0-crd
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --prometheus-collector
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yml
              subPath: policy.yml
      volumes:
        - name: policyfile
          configMap:
            name: sealpolicy
