---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealpolicy
  namespace: powerfulseal
data:
  policy.yml: |-
    config:
      runStrategy:
        minSecondsBetweenRuns: 30
        maxSecondsBetweenRuns: 300
    scenarios: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulseal
  namespace: powerfulseal
spec:
  selector:
    matchLabels:
      name: powerfulseal
  replicas: 1
  template:
    metadata:
      labels:
        name: powerfulseal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      serviceAccountName: powerfulseal
      containers:
        - name: powerfulseal
          imagePullPolicy: Always
          image: powerfulseal/powerfulseal:3.1.0
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --prometheus-collector
          env:
          # in order to allow PowerfulSeal to not accidentally self-destruct
          # give it the pod name
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          # and the host ip
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yml
              subPath: policy.yml
      volumes:
        - name: policyfile
          configMap:
            name: sealpolicy
