---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: powerfulseal
  name: powerfulseal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powerfulseal
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  - deployments
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: powerfulseal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: powerfulseal
subjects:
- kind: ServiceAccount
  name: powerfulseal
  namespace: default
