# this is the namespace where powerfulseal will create things
# it will have full power over this namespace
apiVersion: v1
kind: Namespace
metadata:
  name: powerfulseal-sandbox

# role to do all and anything in powerfulseal-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: powerfulseal-sandbox
  namespace: powerfulseal-sandbox
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: powerfulseal-sandbox
  namespace: powerfulseal-sandbox
subjects:
  - kind: ServiceAccount
    name: powerfulseal
    namespace: powerfulseal
roleRef:
  kind: Role
  name: powerfulseal-sandbox
  apiGroup: rbac.authorization.k8s.io
---
